In [1]:
# Task 1 

# Import pandas library
import pandas as pd 

# Import numpy library
import numpy as np

In [2]:
# Create a dictionary containing the project DataFrame data
project_data = {
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
}

In [3]:
# Convert the dictionary into pandas DataFrame 
project_df = pd.DataFrame(project_data)

In [4]:
# Display the Project DataFrame 
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [5]:
# Create a dictionary containing the Employee DataFrame data
employee_data = {
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxemburg","Tom Sabestine","Nina Adgra","Amy Johnny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]
}

In [6]:
# Convert the employee dictionary into a pandas DataFrame
employee_df = pd.DataFrame(employee_data)

In [7]:
# Display the Employee DataFrame
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxemburg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005       Amy Johnny      F   Madrid   30

In [8]:
# Create a dictionary containing the Seniority Level DataFrame data
seniority_data = {
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]
}

In [9]:
# Convert the seniority dictionary into a pandas DataFrame
seniority_df = pd.DataFrame(seniority_data)

In [10]:
# Display the Seniority Level DataFrame
seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [11]:
# Save the Project DataFrame as a CSV file
project_df.to_csv("Project_DataFrame.csv", index=False)
# Save the Employee DataFrame as a CSV file
employee_df.to_csv("Employee_DataFrame.csv", index=False)
# Save the Seniority Level DataFrame as a CSV file
seniority_df.to_csv("Seniority_DataFrame.csv", index=False)

In [12]:
# Import the os module to interact with the operating system
import os
for filename in ["Project_DataFrame.csv", "Employee_DataFrame.csv", "Seniority_DataFrame.csv"]:
    print(filename, "saved:", os.path.exists(filename))

Project_DataFrame.csv saved: True
Employee_DataFrame.csv saved: True
Seniority_DataFrame.csv saved: True

In [13]:
# Task 2 

# Read the Project DataFrame from the CSV file
project_df = pd.read_csv("Project_DataFrame.csv")

In [14]:
# Display the Project DataFrame
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [15]:
# Initialize an empty list to collect non-missing cost values
cost_list = []

# Loop through each row of the Project DataFrame
for i in range(len(project_df)):

    # If cost is not missing
    if pd.notna(project_df.loc[i, "Cost"]):
        # Add the current Cost to the list
        cost_list.append(project_df.loc[i, "Cost"])

    # If cost is missing
    else:
        # Compute running average using numpy so far
        running_avg = np.mean(cost_list)
        # Replace the missing value with the running average
        project_df.loc[i, "Cost"] = running_avg
        # Add this computed value to the list too, so it's included in the next running average
        cost_list.append(running_avg)

In [16]:
# Display the updated Project DataFrame after replacing missing values
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [17]:
# Task 3 

# Read the Employee DataFrame from the CSV file
employee_df = pd.read_csv("Employee_DataFrame.csv")

In [18]:
# Display the Employee DataFrame
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxemburg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005       Amy Johnny      F   Madrid   30

In [19]:
# Split the Name column into First Name and Last Name columns
employee_df[["First Name", "Last Name"]] = employee_df["Name"].str.split(" ", n=1, expand=True)

In [20]:
# Remove the original Name column from the DataFrame
employee_df = employee_df.drop("Name", axis=1)

In [21]:
# Display the updated Employee DataFrame
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxemburg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy     Johnny

In [22]:
# Task 4 

# Read the Seniority Level DataFrame from the CSV file
seniority_df = pd.read_csv("Seniority_DataFrame.csv")

In [23]:
# Merge the Project and Employee DataFrames using the ID column
Final = pd.merge(project_df, employee_df, on="ID")

In [24]:
# Merge the Final DataFrame with the Seniority DataFrame using the ID column
Final = pd.merge(Final, seniority_df, on="ID")

In [25]:
# Display the merged Final DataFrame
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxemburg,2
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johnny,3
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxemburg,2
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johnny,3
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johnny,3

In [26]:
# Task 5
# Calculate a 5% bonus for employees whose project status is Finished, using np.where
Final["Bonus"] = np.where(Final["Status"] == "Finished", Final["Cost"] * 0.05, 0)

In [27]:
# Display the Final DataFrame with the Bonus column
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxemburg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johnny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxemburg,2,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johnny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johnny,3,10000.0

In [28]:
# Task 6

# find the set of employee IDs that have at least one Failed project
failed_ids = Final.loc[Final["Status"] == "Failed", "ID"].unique()

In [29]:
# demote by 1 — apply to EVERY row of an employee who has any failed project, so the same ID gets a consistent Designation Level across all its rows
Final["Designation Level"] = np.where(
    Final["ID"].isin(failed_ids),
    Final["Designation Level"] + 1,
    Final["Designation Level"]
)

In [30]:
# find IDs (not just rows) whose Designation Level is now above 4
ids_to_drop = Final.loc[Final["Designation Level"] > 4, "ID"].unique()

In [31]:
# drop the entire employee (all their rows), not just the offending row
Final = Final[~Final["ID"].isin(ids_to_drop)]

In [32]:
# Display the updated Final DataFrame after modifying the Designation Level
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,3,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxemburg,3,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,4,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johnny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxemburg,3,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johnny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,4,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,3,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,4,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,3,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johnny,3,10000.0

In [33]:
# Task 7 

# Add the prefix "Mr." to the First Name of all male employees
Final.loc[Final["Gender"] == "M", "First Name"] = "Mr. " + Final["First Name"]

In [34]:
# Add the prefix "Mrs." to the First Name of all female employees
Final.loc[Final["Gender"] == "F", "First Name"] = "Mrs. " + Final[ "First Name"]

In [35]:
# Remove the Gender column from the Final DataFrame
Final = Final.drop("Gender", axis=1)

In [36]:
# Display the updated Final DataFrame
Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,3,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxemburg,3,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,4,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johnny,3,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxemburg,3,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johnny,3,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,4,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,3,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,4,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johnny,3,10000.0

In [37]:
# Task 8

# Promote designation level by 1 for the employees whose age is more than 29 years using IF condition 
def promote(row):
    # If employee's age is more than 29, promote (lower number = higher rank on this scale)
    if row["Age"] > 29:
        return max(row["Designation Level"] - 1, 1)  # promote, but never go below level 1
    else:
        return row["Designation Level"]

In [38]:
# Apply the function row-wise using the IF condition above
Final["Designation Level"] = Final.apply(promote, axis=1)

In [39]:
# Display the updated Final DataFrame after promoting eligible employees
Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,3,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxemburg,3,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,4,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johnny,2,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxemburg,3,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johnny,2,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,4,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,3,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,4,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johnny,2,10000.0

In [40]:
# Task 9 

# Calculate the total project cost for each employee by grouping the data using ID and First Name
TotalProjCost = Final.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

In [41]:
# Rename the Cost column to Total Cost
TotalProjCost.rename(columns={"Cost": "Total Cost"}, inplace=True)

In [42]:
# Display the Total Project Cost DataFrame
TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

In [43]:
# Task 10

# Display all employees whose City name contains the letter 'o'
Final[Final["City"].str.contains("o", case=False)]

#case=False makes the search case-insensitive.

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxemburg,3,0.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxemburg,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000.0